### ISSUE TITLE
Animating content with HTMX

### ISSUE THREAD

**Issue by jonnyjones99** [hay-i/chronologger#26]
I think this [package](https://htmx.org/extensions/class-tools/) will be important for dynamically adding/removing classes using HTMX.

We want to keep the application looking professional and not over use animations- but I think subtle animations are quite important for a nice, smooth user experience.

**Comment by haydenrou** [comment]
Agreed, when creating a PR for this lets both add the extension and use it somewhere to demonstrate it working. Perhaps a fade on the modal opening or something.
